---
title: "CodeBook"
output: html_document
---
Variables description
------------------------------------------

The data represents means and standard deviations of experiment measurements. There is 14220 observations of 4 variables: subject, activity, measure and value. 

Variables:

  - subject 
  
    The number assigned to the subject, 1-30
    
  - activity
  
    One of 6 activities during which the measurements were performed
      - laying
      - standing
      - sitting
      - walking
      - walking upstairs
      - walking downstairs
      
  - measure
  
    For every subject and activity there are 79 different measurements - means and standard deviations for triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration, triaxial Angular velocity from the gyroscope. Variables are given in time and frequency domains. 
    
    Measure levels are:
    
      - "tBodyAcc-mean()-X"
      - "tBodyAcc-mean()-Y"
      - "tBodyAcc-mean()-Z"
      - "tBodyAcc-std()-X"
      - "tBodyAcc-std()-Y"
      - "tBodyAcc-std()-Z"
      - "tGravityAcc-mean()-X"
      - "tGravityAcc-mean()-Y"
      - "tGravityAcc-mean()-Z"
      - "tGravityAcc-std()-X"
      - "tGravityAcc-std()-Y"
      - "tGravityAcc-std()-Z"
      - "tBodyAccJerk-mean()-X"
      - "tBodyAccJerk-mean()-Y"
      - "tBodyAccJerk-mean()-Z"
      - "tBodyAccJerk-std()-X"
      - "tBodyAccJerk-std()-Y"
      - "tBodyAccJerk-std()-Z"
      - "tBodyGyro-mean()-X"
      - "tBodyGyro-mean()-Y"
      - "tBodyGyro-mean()-Z"
      - "tBodyGyro-std()-X"
      - "tBodyGyro-std()-Y"
      - "tBodyGyro-std()-Z"
      - "tBodyGyroJerk-mean()-X"
      - "tBodyGyroJerk-mean()-Y"
      - "tBodyGyroJerk-mean()-Z"
      - "tBodyGyroJerk-std()-X"
      - "tBodyGyroJerk-std()-Y"
      - "tBodyGyroJerk-std()-Z"
      - "tBodyAccMag-mean()"
      - "tBodyAccMag-std()"
      - "tGravityAccMag-mean()"
      - "tGravityAccMag-std()"
      - "tBodyAccJerkMag-mean()"
      - "tBodyAccJerkMag-std()"
      - "tBodyGyroMag-mean()"
      - "tBodyGyroMag-std()"
      - "tBodyGyroJerkMag-mean()"
      - "tBodyGyroJerkMag-std()"
      - "fBodyAcc-mean()-X"
      - "fBodyAcc-mean()-Y"
      - "fBodyAcc-mean()-Z"
      - "fBodyAcc-std()-X"
      - "fBodyAcc-std()-Y"
      - "fBodyAcc-std()-Z"
      - "fBodyAcc-meanFreq()-X"
      - "fBodyAcc-meanFreq()-Y"
      - "fBodyAcc-meanFreq()-Z"
      - "fBodyAccJerk-mean()-X"
      - "fBodyAccJerk-mean()-Y"
      - "fBodyAccJerk-mean()-Z"
      - "fBodyAccJerk-std()-X"
      - "fBodyAccJerk-std()-Y"
      - "fBodyAccJerk-std()-Z"
      - "fBodyAccJerk-meanFreq()-X"
      - "fBodyAccJerk-meanFreq()-Y"
      - "fBodyAccJerk-meanFreq()-Z"
      - "fBodyGyro-mean()-X"
      - "fBodyGyro-mean()-Y"
      - "fBodyGyro-mean()-Z"
      - "fBodyGyro-std()-X"
      - "fBodyGyro-std()-Y"
      - "fBodyGyro-std()-Z"
      - "fBodyGyro-meanFreq()-X"
      - "fBodyGyro-meanFreq()-Y"
      - "fBodyGyro-meanFreq()-Z"
      - "fBodyAccMag-mean()"
      - "fBodyAccMag-std()"
      - "fBodyAccMag-meanFreq()"
      - "fBodyBodyAccJerkMag-mean()"
      - "fBodyBodyAccJerkMag-std()"
      - "fBodyBodyAccJerkMag-meanFreq()"
      - "fBodyBodyGyroMag-mean()"
      - "fBodyBodyGyroMag-std()"
      - "fBodyBodyGyroMag-meanFreq()"
      - "fBodyBodyGyroJerkMag-mean()"
      - "fBodyBodyGyroJerkMag-std()"
      - "fBodyBodyGyroJerkMag-meanFreq()"
           
  - value
    
    Value is the mean value of measurements for every subject, every activity and avery measurement type. Acceleration measurements are in standard gravity units 'g'. The angular velocity measurements coming from gyroscope are in radians/second. 


Data transformations
------------------------------------------    
In order to create a tidy data set, several actions on the initial data were performed. First we created one data set from all read data:

```
#merging the sets
x <- rbind(testx, trainx)
y <- rbind(testy, trainy)
subject <- rbind(subjecttest, subjecttrain)

#creating one data set
dat <- cbind(x,y,subject)
```

After that, we extracted only the means and standard deviations of all measurements and corresponding features

```
#extracting only the means and standard devaition measurements, from data and features
m <- grep("mean", as.character(features[,2]))
s <- as.integer(grep("std", as.character(features[,2])))
d <- sort(c(m,s))
dat <- dat[,d]
nn <- as.character(features[,2])
nn <- nn[d]

```

Instead of having a number for activity, we gave intuitive names to the activities 

```
#renaming the activities, based on activity_labels.txt
y <- factor(y[,1])
levels(y) <- c("walking", "walkingupstairs", "walkingdownstairs", "sitting", "standing", "laying")
y <- as.character(y)

```

To get long and tidy data set, we did following:

```
#Getting long tidy data set
library(reshape2)
dat <- melt(dat, id = c("subject", "activity"), na.rm = T)
dat <- dcast(dat, subject + activity ~ variable, mean)
dat <- melt(dat, id = c("subject", "activity"))
names(dat) <- c("subject", "activity", "measure", "value")
```
The data table obtained this way is written in 'data.txt'

Acknowledgment
---------------------------------------------------
The data used was taken from 

Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

          
            